### ISSUE TITLE
Bug: route_matrix Status 403

### ISSUE THREAD

**Issue by Arnold-Kakas** [munterfi/hereR#166]
`route_matrix()` returns
Warning message:
In .parse_response(i, out$responses()[[i]]) :
  https://matrix.router.hereapi.com/v8/matrix: Request 'id = 1' failed. 
  Status 403; Forbidden; Request forbidden -- authorization will not help.
  
while `route()` works. I tried examples from documentation with same result.
this does not work:
mat <- route_matrix(
  origin = poi)

this works:
to <- poi[rep(seq_len(nrow(poi)), nrow(poi)), ]
from <- poi[rep(seq_len(nrow(poi)), each = nrow(poi)), ]
idx <- apply(to != from, any, MARGIN = 1)
to <- to[idx, ]
from <- from[idx, ]

routes <- route(
    origin = from, destination = to, results = 3,
    transport_mode = "car", url_only = TRUE
)

**Comment by munterfi** [comment]
Hi @Arnold-Kakas, thanks for reporting.

It seems like the issue is related to the permissions set on the API key for newly created applications on the HERE platform. My older API key still works fine, but when I generate a new app and key, I encounter the same behavior.

```json
{
	"title": "Forbidden.",
	"status": 403,
	"code": "403403",
	"cause": "App XXXXXX credentials do not authorize access to perform lama_matrix action via SERVICE-XXXXXX or to perform invoke action on hrn:here:service::olp-here:matrix-routing-8 via SERVICE-XXXXXX because no matching permissions found for the identity, its groups and roles, or the realm.",
	"action": "Add/Share the necessary permissions to the identity.",
	"error": "Forbidden",
	"details": [
	],
	"error_description": "These credentials do not authorize access"
}
```

After searching the HERE platform, I couldn’t find any specific options to enable matrix routing for newly created applications. It might be best to contact HERE platform support to clarify how to enable matrix routing permissions for new API keys.

It is also possible that matrix routing may have been restricted from the free tier. However, according to [this page](https://www.here.com/get-started/pricing/limited-plan-restrictions), matrix routing requests should still be allowed with a limit of one request per second in the free plan.

I hope this helps.

**Comment by munterfi** [comment]
Hi @Arnold-Kakas, do you have any updates from the HERE support on this issue?

**Comment by munterfi** [comment]
Too bad, thanks for the update.
